variable "namespace" {
  type        = string
  description = "Namespace of the project, i.e. arc"
}

variable "environment" {
  type        = string
  description = "Name of the environment, i.e. dev, stage, prod"
}

variable "name" {
  description = "Name for the Redshift Serverless resources"
  type        = string
}

variable "namespace_name" {
  description = "The name of the Redshift Serverless namespace"
  type        = string
  default     = null
}

variable "workgroup_name" {
  description = "The name of the Redshift Serverless workgroup"
  type        = string
  default     = null
}

variable "db_name" {
  description = "The name of the database to create"
  type        = string
}

variable "admin_username" {
  description = "Username for the admin user"
  type        = string
  sensitive   = true
}

variable "admin_password" {
  description = "Password for the admin user. If null and manage_user_password is null, a random password should be generated by the calling module"
  type        = string
  sensitive   = true
  default     = null
}

variable "manage_user_password" {
  description = "Set to true to allow AWS to manage the admin user password in Secrets Manager"
  type        = bool
  default     = null
}

variable "base_capacity" {
  description = "The base data warehouse capacity in Redshift Processing Units (RPUs)"
  type        = number
  default     = 32
}

variable "max_capacity" {
  description = "The maximum data warehouse capacity in Redshift Processing Units (RPUs)"
  type        = number
  default     = 512
}

variable "publicly_accessible" {
  description = "If true, the workgroup can be accessed from a public network"
  type        = bool
  default     = false
}

variable "subnet_ids" {
  description = "List of subnet IDs for the Redshift Serverless workgroup"
  type        = list(string)
  default     = []
}

variable "vpc_id" {
  description = "ID of the VPC for Redshift Serverless"
  type        = string
  default     = null
}

variable "vpc_security_group_ids" {
  description = "A list of Virtual Private Cloud (VPC) security groups to be associated with the workgroup"
  type        = list(string)
  default     = []
}

variable "kms_key_id" {
  description = "The ARN for the KMS encryption key"
  type        = string
  default     = null
}

variable "ingress_rules" {
  description = "A list of ingress rules for the security group."
  type = list(object({
    from_port   = number
    to_port     = number
    protocol    = string
    cidr_blocks = list(string)
  }))
  default = []
}

variable "egress_rules" {
  description = "A list of egress rules for the security group."
  type = list(object({
    from_port   = number
    to_port     = number
    protocol    = string
    cidr_blocks = list(string)
  }))
  default = []
}

variable "security_group_name" {
  description = "Name for the security group"
  type        = string
  default     = ""
}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}
